name: Deploy ERPG Keycloakify Theme JAR

on:
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK
              uses: actions/setup-java@v4
              with:
                  distribution: "temurin"
                  java-version: "17"

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Enable Corepack (for Yarn 4+)
              run: corepack enable

            - name: Install dependencies using Yarn 4
              run: yarn install --immutable

            - name: Build Keycloak theme
              run: yarn run build-keycloak-theme

            - name: Extract theme name and registry URL from package.json
              id: extract
              run: |
                  THEME_NAME=$(grep '"name"' package.json | head -1 | sed 's/.*: "\(.*\)",*/\1/')
                  REPO_URL=$(grep '"registry"' package.json | head -1 | sed 's/.*: "\(.*\)".*/\1/')
                  echo "theme_name=$THEME_NAME" >> "$GITHUB_OUTPUT"
                  echo "repo_url=$REPO_URL" >> "$GITHUB_OUTPUT"

            - name: Verify JAR file exists
              run: |
                  JAR_FILE="dist_keycloak/${{ steps.extract.outputs.theme_name }}.jar"
                  if [ ! -f "$JAR_FILE" ]; then
                    echo "Error: JAR file not found. Please check the build."
                    exit 1
                  fi

            - name: Setup Maven Wrapper
              run: chmod +x ./mvnw

            - name: Deploy to Maven repository
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  ./mvnw -B --quiet deploy:deploy-file \
                    -s .github/mvn-settings.xml \
                    -DrepositoryId=github \
                    -Durl=${{ steps.extract.outputs.repo_url }} \
                    -Dfile=dist_keycloak/${{ steps.extract.outputs.theme_name }}.jar
